server:
  port: 8095

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_search
    username: root
    password: Letmechange123!
  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: TB-SEARCH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka